AdminPanel/Models/Employee.cs
namespace  AdminPanel.Models
{ 
    public class Employee
    {
        public string? Sys_Code { get; set; } // UDD_Emp_Sys_Code primary key
        public string? EmployeeCode { get; set; } // UDD_EmployeeCode
        public string? OrgCode { get; set; } // UDD_OrgCode
        public string? First_Name { get; set; } // VARCHAR(30) NOT NULL
        public string? Middle_Name { get; set; } // VARCHAR(30)
        public string? Last_Name { get; set; } // VARCHAR(40) NOT NULL

        public string? Full_Name { get; set; } // VARCHAR(40) NOT NULL
        public string? Alice_Name { get; set; } // VARCHAR(40) NOT NULL
        public string? Emp_Status { get; set; } // VARCHAR(15) NOT NULL
        public string? Salesmen { get; set; } // VARCHAR(3) NOT NULL
        public string? Co_Email_ID { get; set; } // VARCHAR(100) NOT NULL
        public string? Mobile_No { get; set; } // INT NOT NULL
        public string? Reason_for_Resignation { get; set; } // VARCHAR(50)
        public string? Emp_photoCode { get; set; } // UDD_EMP_PHOTO_SIGNATURE_SYS_CODE
        public string? Status { get; set; } // CHAR(1) NOT NULL
        public string? Date_of_Joining { get; set; } // DATE
        public string? Probation_Period { get; set; } // VARCHAR(3)
        public string? Professional_Status { get; set; } // VARCHAR(15)
        public string? National_ID { get; set; } // VARCHAR(50)
        public string? Transfer_Date { get; set; } // DATE
        public string? Employment_End_Date { get; set; } // DATE
        public string? BranchCode { get; set; } // UDD_BRNSysCod
        public string? DepartmentCode { get; set; } // UDD_DEPCode
        public string? Department_Head_Code { get; set; } // UDD_Emp_Sys_Code
        public string? Reporting_To_Code { get; set; } // UDD_Emp_Sys_Code
        public string? Designation_Start_Date { get; set; }
        public string? DesignationCode { get; set; } // UDD_DESGCode
        public string? Designation_Qualifier { get; set; } // VARCHAR(100)
        public string? Job_Description { get; set; } // VARCHAR(2000)
        public string? Payroll_Employee_ID { get; set; } // VARCHAR(50)
        public string? Date_Of_Birth { get; set; } // DATE NOT NULL
        public string? Aadhar_No { get; set; } // VARCHAR(12) NOT NULL
        public string? PAN_No { get; set; } // VARCHAR(10) NOT NULL
        public string? Gender { get; set; } // VARCHAR(10) NOT NULL
        public string? UAN_No { get; set; } // VARCHAR(50)
        public string? Nationality { get; set; } // VARCHAR(50) NOT NULL
        public string? Religion { get; set; } // VARCHAR(50)
        public string? Marital_Status { get; set; } // VARCHAR(10)
        public string? Wedding_Annive { get; set; } // DATE
        public string? Office_Phone_No { get; set; } // VARCHAR(15)
        public string? Personal_Email_ID { get; set; } // VARCHAR(100) NOT NULL
        public string? Personal_Mobile_No { get; set; } // VARCHAR(10) NOT NULL
        public string? Home_Town { get; set; } // VARCHAR(50)
        public string? Airport_Name { get; set; } // VARCHAR(100)
        public string? Personal_Address { get; set; } // VARCHAR(500) NOT NULL
        public string? Phone_Number { get; set; } // VARCHAR(30)
        public string? Contact_Address { get; set; } // VARCHAR(500)
        public string? Emergency_Contact_Person { get; set; } // VARCHAR(100) NOT NULL
        public string? Emergency_Contact_Address { get; set; } // VARCHAR(500)
        public string? Emergency_Contact_No { get; set; } // VARCHAR(30) NOT NULL
        public string? Bank_AC_No { get; set; } // VARCHAR(50) NOT NULL
        public string? IFSC_Code { get; set; } // VARCHAR(11) NOT NULL
        public string? Bank_Name { get; set; } // VARCHAR(100) NOT NULL
        public string? Bank_Address { get; set; } // VARCHAR(500)
       
        public string? Sys_Created_By { get; set; } // UDD_UserID
        public string? Sys_Created_On { get; set; } // DATETIME
        public string? Sys_Modified_By { get; set; } // UDD_UserID
        public string? Sys_Modified_On { get; set; } // DATETIME

        public byte[] Photo { get; set; } 
    }
}

AdminPanel/Controllers/EmployeeMasterController.cs
using AdminPanel.CommonRepo;
using AdminPanel.Models;
using AdminPanel.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace AdminPanel.Controllers
{
   
    [Authorize]
    [AuthorizeUser]
    public class EmployeeMasterController : Controller
    {
        IGeneral general;
        IEmployee Employee;
        IUserMaster userMaster;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public EmployeeMasterController(IEmployee _Employee, IGeneral _general, IUserMaster userMaster, IHttpContextAccessor httpContextAccessor)
        {
            Employee = _Employee;
            general = _general;
            this.userMaster = userMaster;
            _httpContextAccessor = httpContextAccessor;
        }


        [HttpGet]
        public IActionResult Employee_Form(string Id = "")
        {   // Master Form
            try
            {
                Employee d= new Employee(); 
                ViewBag.YesNoDropDown = CommonDropdown.GetYesNoDropdown();
                ViewBag.Status = CommonDropdown.GetStatusDropdown();
                ViewBag.EmpStatus = CommonDropdown.Get_EmployeeStatusDropdown();
                //Tabs details
                ViewBag.BranchLocation = Employee.Get_Branch_Location_Drop();
                ViewBag.Department = Employee.Get_Department_Drop();
                ViewBag.Reporting_To = Employee.Get_Reportin_To_Drop();
                ViewBag.Department_Head = Employee.Get_Department_Head_Code_Drop();
                ViewBag.Designation = Employee.Get_Designation_Drop();
                ViewBag.Currency = Employee.Get_CurrencyList_For_Cureency_Drop();
                // Personal
                ViewBag.NationalityDrop = Employee.Get_CountryList_For_Nationality_Drop(2);
                ViewBag.ORG = userMaster.GetOrganizationDropDownbyorgid();

                if (Id != "")
                {
                    Employee obj = Employee.GetEmployeeById(Id);

                    var photoBase64 = Convert.ToBase64String(obj.Photo);
                    var photoBase64Url = $"data:{"data:image/png"};base64,{photoBase64}";
                    ViewBag.EmpPhoto = photoBase64Url;
                    //GlAccount Details
                    ViewBag.GetGlMappingDetails = Employee.GetEmployee_GL_MappingBy_EmpCode(Id);

                    // Family Details 
                    ViewBag.GetFamilyDetails = Employee.Get_Family_Details_By_Emp_SysCode(Id);

                    //Employee Documents 
                    ViewBag.GetEmpDocDetails = Employee.GetEmp_Documents_By_EmpCode(Id);

                    return View(obj);
                }
                var user = _httpContextAccessor.HttpContext.User;

                string orgCode = user.FindFirst("OrgCode")?.Value;
                if (orgCode == "" || orgCode == null)
                {
                    return View();
                }
                d.OrgCode = orgCode;
                return View(d);

            }
            catch (Exception ex)
            {

                general.Write_Log_Into_Txt(ex.Message, "EmployeeMasterController");
                general.InsertExcepstionlog(ex.Message, "EmployeeMasterController");
                return View("Error");
            }
        }

        [HttpPost]
        public IActionResult Employee_Form(Employee obj, IFormFile Emp_photoCode)
        {
            try
            {
                ViewBag.ORG = userMaster.GetOrganizationDropDownbyorgid();
                ViewBag.YesNoDropDown = CommonDropdown.GetYesNoDropdown();
                ViewBag.Status = CommonDropdown.GetStatusDropdown();
                ViewBag.EmpStatus = CommonDropdown.Get_EmployeeStatusDropdown();
                //Tabs details
                ViewBag.BranchLocation = Employee.Get_Branch_Location_Drop();
                ViewBag.Department = Employee.Get_Department_Drop();
                ViewBag.Reporting_To = Employee.Get_Reportin_To_Drop();
                ViewBag.Department_Head = Employee.Get_Department_Head_Code_Drop();
                ViewBag.Currency = Employee.Get_CurrencyList_For_Cureency_Drop();
                ViewBag.Designation = Employee.Get_Designation_Drop();
                ViewBag.NationalityDrop = Employee.Get_CountryList_For_Nationality_Drop(2);
                ResponceMessage RespMsg = Employee.InsertUpadte_Employee(obj, Emp_photoCode);
                if (RespMsg==null)
                {
                    Employee d= new Employee();
                    var user = _httpContextAccessor.HttpContext.User;

                    string orgCode = user.FindFirst("OrgCode")?.Value;
                    if (orgCode == "" || orgCode == null)
                    {
                        return View();
                    }
                    d.OrgCode = orgCode;
                    return View(d);

                    
                }
                if(RespMsg.code==0)
                {
                    TempData["Output"] = "Record submitted successfully.";
                }
                if (RespMsg.code == 1)
                {
                    TempData["Output"] = "Record updated successfully";
                }
                if (RespMsg.code == 2)
                {
                    TempData["Output"] = "Co-Email id already Exits";
                    return View(obj);
                }
                else if (RespMsg.code == -1)
                {
                    TempData["Output"] = "Something went wrong. Please try again.";
                }

                var photo = RespMsg.Message.Photo;
               // int EmpId = Convert.ToInt32( RespMsg.Message.Sys_Code);
                //GlAccount Details
                ViewBag.GetGlMappingDetails = Employee.GetEmployee_GL_MappingBy_EmpCode(RespMsg.Message.Sys_Code);

                // Family Details 
                ViewBag.GetFamilyDetails = Employee.Get_Family_Details_By_Emp_SysCode(RespMsg.Message.Sys_Code);

                //Employee Documents 
                ViewBag.GetEmpDocDetails = Employee.GetEmp_Documents_By_EmpCode(RespMsg.Message.Sys_Code);
                if (photo != null && photo.Length > 0)
                {
                    
                        var photoBase64 = Convert.ToBase64String(photo);
                        var photoBase64Url = $"data:{"data:image/png"};base64,{photoBase64}";
                        ViewBag.EmpPhoto = photoBase64Url;
                    
                }
                else
                {
                    ViewBag.EmpPhoto = null;
                }
                return View(RespMsg.Message);

            }
            catch (Exception ex)
            {

                general.Write_Log_Into_Txt(ex.Message, "EmployeeMasterController");
                general.InsertExcepstionlog(ex.Message, "EmployeeMasterController");
                return View("Error");
            }

        }


        [HttpGet]
        public IActionResult Employee_List()
        {
            try
            {
                ViewBag.EmployeeList = Employee.GetEmployeeList();
                return View();
            }
            catch (Exception ex)
            {

                general.Write_Log_Into_Txt(ex.Message, "EmployeeMasterController");
                general.InsertExcepstionlog(ex.Message, "EmployeeMasterController");
                return View("Error");
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            try
            {
                bool respo = Employee.Delete(id);
                if (respo)
                {
                    TempData["Output"] = "Deleted successfully.";
                }

                return Json(respo);
            }
            catch (Exception er)
            {
                general.Write_Log_Into_Txt(er.Message, "EmployeeMasterController");
                general.InsertExcepstionlog(er.Message, "EmployeeMasterController");
                return View("Error");
            }

        }

        [HttpGet]
        public IActionResult Employee_Professional()
        {
            return View();
        }


        [HttpGet]
        public IActionResult Employee_Personal()
        {
            return View();
        }


        [HttpGet]
        public IActionResult Employee_Accounts()
        {
            try
            {
                ViewBag.Status = CommonDropdown.GetStatusDropdown();
                ViewBag.BranchLocation = Employee.Get_Branch_Location_Drop();

                return View();
            }
            catch (Exception ex)
            {

                general.Write_Log_Into_Txt(ex.Message, "EmployeeMasterController");
                general.InsertExcepstionlog(ex.Message, "EmployeeMasterController");
                return View("Error");
            }
        }


        //Employee Documents
        #region Employee Documents
        [HttpGet]
        public IActionResult Employee_Documents()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Employee_Documents(IFormFile Emp_documents1, string document_type, string Sys_Code_Doc, string Sys_Code)
        {
            if (Emp_documents1 != null)
            {
                List<Employee_Doc> EmpDocList = Employee.InsertUpadte_Emp_Documents(Emp_documents1, document_type, Sys_Code_Doc, Sys_Code);
                return Json(EmpDocList);
            }

            return View();
        }

        public IActionResult Employee_Documents_Check(string Sys_Code, string document_type)
        {
            if (Sys_Code != null && document_type != null)
            {
                bool response = Employee.Check_DocumentType(Sys_Code, document_type);
                return Json(response);
            }

            return View();
        }

        [HttpGet]
        public IActionResult Delete_Employee_Documents(string Sys_Code)
        {
            if (Sys_Code != null)
            {

AdminPanel/Views/EmployeeMaster/Employee_List.cshtml
@using Syncfusion.EJ2
@addTagHelper *, Syncfusion.EJ2
@{
    ViewData["Title"] = "Employeelist";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h4 class="p-2 m-0">
                Employee List
            </h4>
        </div>
    </div>
</div>

@{
    List<object> GridCommands = new List<object>();

    GridCommands.Add(new { type = "Edit", buttonOption = new { iconCss = "e-icons e-edit btnEdit", cssClass = "e-flat" } });

    GridCommands.Add(new { type = "Delete", buttonOption = new { iconCss = "e-icons e-delete btnDelete", cssClass = "e-flat" } });
}


@{
    string o = TempData["Output"] as string;
    bool showToast = !string.IsNullOrEmpty(o);
    string toastClass = string.Empty;

    if (showToast)
    {

        if (o.Contains("Error"))
        {
            toastClass = "bg-danger";
        }
        else
        {
            toastClass = "bg-success";
        }
    }
}

<style>
    .bg-success {
        background-color: #28a745 !important;
        color: white;
    }


    .bg-danger {
        background-color: #dc3545 !important;
        color: white;
    }
</style>



@if (showToast)
{
    <ejs-toast id="element" cssClass="@toastClass" content="@o"></ejs-toast>
}




<div id="Dilog" class="w-25"></div>
<div class="container-fluid mt-2 ">

    @* //dataSource="@ViewBag.OrgData" *@
    <ejs-grid id="Grid" dataSource="@ViewBag.EmployeeList" allowSorting="true" allowPaging="true" allowResizing="true" allowExcelExport="true" toolbar="@(new List<string>() {"Search","CustomButton"  })">
        <e-grid-editsettings></e-grid-editsettings>
        <e-grid-pageSettings pageSize="5" pageSizes="true" />
        <e-grid-columns>
            <e-grid-column headerText="Option" width="105" commands="GridCommands"></e-grid-column>
            <e-grid-column field="Sys_Code" isPrimaryKey="true" visible="false" headerText="Sys Code" width="105" textAlign="Right"></e-grid-column>
            <e-grid-column field="EmployeeCode" headerText="Employee Code" textAlign="Left" width="150"></e-grid-column>
            <e-grid-column field="OrgCode" headerText="Org Code" textAlign="Left" width="150"></e-grid-column>
            <e-grid-column field="First_Name" headerText="First Name" textAlign="Left" width="150"></e-grid-column>
            <e-grid-column field="Middle_Name" headerText="Middle Name" textAlign="Left" width="150"></e-grid-column>
            <e-grid-column field="Last_Name" headerText="Last Name" textAlign="Left" width="150"></e-grid-column>
            <e-grid-column field="Emp_Status" headerText="Emp Status" textAlign="Left" width="150"></e-grid-column>
            <e-grid-column field="Salesmen" headerText="Salesmen" textAlign="Left" width="150"></e-grid-column>
            <e-grid-column field="Co_Email_ID" headerText="Email ID" textAlign="Left" width="150"></e-grid-column>
            <e-grid-column field="Mobile_No" headerText="Mobile No" textAlign="Left" width="150"></e-grid-column>
            <e-grid-column field="Reason_for_Resignation" headerText="Reason for Resignation" textAlign="Left" width="150"></e-grid-column>
            <e-grid-column field="Emp_photoCode" headerText="Photo Code" textAlign="Left" width="150"></e-grid-column>
            <e-grid-column field="Status" headerText="Status" textAlign="Center" width="150"></e-grid-column>
            @* <e-grid-column field="Sys_Created_By" headerText="Created By" textAlign="Center" width="150"></e-grid-column>
            <e-grid-column field="Sys_Created_On" headerText="Created On" textAlign="Center" width="150"></e-grid-column>
            <e-grid-column field="Sys_Modified_By" headerText="Modified By" textAlign="Center" width="150"></e-grid-column>
            <e-grid-column field="Sys_Modified_On" headerText="Modified On" textAlign="Center" width="150"></e-grid-column> *@
        </e-grid-columns>

    </ejs-grid>

</div>


<script>


    //For Toaster---
    document.addEventListener('DOMContentLoaded', function () {
        var showToast = @showToast.ToString().ToLower();

        if (showToast) {
            var toastObj = document.getElementById('element').ej2_instances[0];

            // Set the toaster position to top-right
            toastObj.position = {
                X: 'Right',
                Y: 'Top'
            };

            toastObj.show();
        }
    });

    var id;


    $(document).ready(function () {

        var spanElement = $('<span class="e-btn-icon e-add e-icons e-icon-left "></span>');

        $(".e-tbar-btn-text").text("Add New");

        $("#Grid_CustomButton").prepend(spanElement);


        $("#Grid_CustomButton").on("click", function () {


            window.location.href = '@Url.Action("Employee_Form", "EmployeeMaster")';
        });
    });

    // Handle Edit and Delete
    function handleEditCommand(rowData) {

        // Example: Implement logic to handle edit command
        var grid = document.getElementById("Grid").ej2_instances[0];
        var data = grid.getRowObjectFromUID(rowData).data;
        console.log("Edit command clicked", data.Sys_Code);
        var EditId = data.Sys_Code;
        if (EditId != "") {
            window.location.href = '@Url.Action("Employee_Form", "EmployeeMaster")' + '?Id=' + EditId;
        }



    }

    //delete Functionality sss---------------------------------

    var dialog = new ej.popups.Dialog({
        header: 'Confirm Delete',
        content: '<div>Are you sure you want to delete this record?</div>',
        buttons: [
            { buttonModel: { content: 'Yes', isPrimary: true }, click: onYesButtonClick, id: 'confirmDelete' },
            { buttonModel: { content: 'No' }, click: onNoButtonClick, id: 'cancelDelete' }
        ]

    });


    function clearDialogDiv() {
        var dialogDiv = document.getElementById("Dilog");
        if (dialogDiv) {
            while (dialogDiv.firstChild) {
                dialogDiv.removeChild(dialogDiv.firstChild);
            }
        }
    }


    function onNoButtonClick() {
        dialog.hide()
        clearDialogDiv();
        var popup = document.getElementById('Dilog');
        console.log(popup);
        var popupElement = popup.querySelector('w-25.e-control.e-popup.e-popup-.e-dialog');
        console.log(popupElement);
        if (popupElement) {
            alert("ggg");
            popup.removeChild(popupElement);
        }
    }

    function onYesButtonClick() {

        clearDialogDiv();
        console.log("Yes button clicked", id)

        if (id != "" && id != null) {
            $.ajax({
                "url": '@Url.Action("Delete", "EmployeeMaster")',
                method: "GET",
                data: { Id: id },
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    if (data = true) {
                        console.log(data.Staus);
                        window.location.reload();
                    }

                },
                error: function (err) {
                    window.location.href = errorViewUrl;
                    console.log("error: " + err)
                }

            })
        }
        id = 0;
        //Call Delete Ajax
        id = 0;

        var grid = document.getElementById('Grid').ej2_instances[0];
        grid.refresh();

    }

    function handleDeleteCommand(rowData) {
        clearDialogDiv();
        var grid = document.getElementById("Grid").ej2_instances[0];
        dialog.appendTo('#Dilog');

        var data = grid.getRowObjectFromUID(rowData).data;
        console.log("Delete command clicked", data.Sys_Code);
        id = data.Sys_Code;
        console.log(id);
        if (dialog) {
            dialog.show(); // Show the dialog
        }

    }

    //Event when user Click On Edit or Delete Option Starts
    document.body.addEventListener("click", function (event) {
        var target = event.target;
        if (target.classList.contains("e-editbutton") || target.classList.contains("btnEdit")) {

            var rowData = target.closest("tr").getAttribute("data-uid");
            console.log(rowData);

            handleEditCommand(rowData);
        } else if (target.classList.contains("e-deletebutton") || target.classList.contains("btnDelete")) {

            var rowData = target.closest("tr").getAttribute("data-uid");
            handleDeleteCommand(rowData);
        }
    });





</script>

AdminPanel/Views/EmployeeMaster/Employee_Personal.cshtml
@model AdminPanel.Models.Employee
@using Newtonsoft.Json



@{
    var gender = new string[] { "Male", "Female", "Other" };

    var martial = new string[] { "Single", "Married", "Widowed", "Divorced" };



}

<div class="container-fluid">
    <form id="Personal_Form">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">


            <div class="card rounded">
                <div class="card-body">
                    <div class="row ">



                        <div class=" col-4">
                            <ejs-datepicker id="Date_Of_Birth" placeholder="Date Of Birth*" format="dd-MM-yyyy" floatLabelType=Auto ejs-for="@Model.Date_Of_Birth"></ejs-datepicker>
                            <span asp-validation-for="Date_Of_Birth" class="text-danger"></span>
                        </div>
                        <div class=" col-4">
                            <ejs-textbox id="Aadhar_No" placeholder="Aadhar No*" floatLabelType=Auto ejs-for="@Model.Aadhar_No"></ejs-textbox>
                            <span asp-validation-for="Aadhar_No" maxlength="12" class="text-danger"></span>
                        </div>
                        <div class=" col-4">
                            <ejs-textbox id="PAN_No" placeholder="PAN No*" floatLabelType=Auto ejs-for="@Model.PAN_No"></ejs-textbox>
                            <span asp-validation-for="PAN_No" maxlength="10" class="text-danger"></span>
                        </div>
                        <div class=" col-4">
                            <ejs-dropdownlist id="Gender" floatLabelType=Auto placeholder="Gender" filterBarPlaceholder="Search" ejs-for="@Model.Gender" dataSource="gender" >
                                <e-dropdownlist-fields text="Text" value="Value"></e-dropdownlist-fields>
                            </ejs-dropdownlist>
                            <span asp-validation-for="Gender" class="text-danger"></span>
                        </div>
                        <div class=" col-4">
                            <ejs-textbox id="UAN_No" maxlength="50" placeholder="UAN No" floatLabelType=Auto ejs-for="@Model.UAN_No"></ejs-textbox>
                            <span asp-validation-for="UAN_No" class="text-danger"></span>
                        </div>
                        <div class=" col-4">
                            <ejs-dropdownlist id="Nationality" floatLabelType=Auto placeholder="Nationality*" filterBarPlaceholder="Search" ejs-for="@Model.Nationality" filtering="onfilteringN" dataSource="@ViewBag.NationalityDrop" allowFiltering="true">
                                <e-dropdownlist-fields text="Text" value="Value"></e-dropdownlist-fields>
                            </ejs-dropdownlist>
                            <span asp-validation-for="Nationality" class="text-danger"></span>
                        </div>
                        <div class=" col-4">
                            <ejs-textbox id="Religion" maxlength="50" placeholder="Religion" floatLabelType=Auto ejs-for="@Model.Religion"></ejs-textbox>
                            <span asp-validation-for="Religion" class="text-danger"></span>
                        </div>

                        <div class=" col-4">
                            <ejs-dropdownlist id="Marital_Status" floatLabelType=Auto placeholder="Marital Status" filterBarPlaceholder="Search" ejs-for="@Model.Marital_Status" dataSource="martial">
                                <e-dropdownlist-fields text="Text" value="Value"></e-dropdownlist-fields>
                            </ejs-dropdownlist>
                            <span asp-validation-for="Marital_Status" class="text-danger"></span>
                        </div>
                        <div class=" col-4">
                            <ejs-datepicker id="Wedding_Annive" floatLabelType=Auto format="dd-MM-yyyy" placeholder="Wedding Anniversary" ejs-for="@Model.Wedding_Annive"></ejs-datepicker>
                            <span asp-validation-for="Wedding_Annive" class="text-danger"></span>
                        </div>

                        <div class=" col-4">
                            <ejs-textbox id="Office_Phone_No" maxlength="15" floatLabelType=Auto placeholder="Office Phone No" ejs-for="@Model.Office_Phone_No"></ejs-textbox>
                            <span asp-validation-for="Office_Phone_No" class="text-danger"></span>
                        </div>


                        <div class=" col-4">
                            <ejs-textbox id="Personal_Email_ID" maxlength="100" floatLabelType=Auto placeholder="Personal Email ID*" ejs-for="@Model.Personal_Email_ID"></ejs-textbox>
                            <span asp-validation-for="Personal_Email_ID" class="text-danger"></span>
                        </div>


                        <div class=" col-4">
                            <ejs-textbox id="Personal_Mobile_No" showSpinButton="false" maxlength="10" floatLabelType=Auto placeholder="Personal Mobile No*" ejs-for="@Model.Personal_Mobile_No"></ejs-textbox>
                            <span asp-validation-for="Personal_Mobile_No" class="text-danger"></span>
                        </div>

                        <div class=" col-4">
                            <ejs-textbox id="Home_Town" maxlength="50" placeholder="Home Town" floatLabelType=Auto ejs-for="@Model.Home_Town"></ejs-textbox>
                            <span asp-validation-for="Home_Town" class="text-danger"></span>
                        </div>

                        <div class=" col-4">
                            <ejs-textbox id="Airport_Name" maxlength="100" placeholder="Airport Name" floatLabelType=Auto ejs-for="@Model.Airport_Name"></ejs-textbox>
                            <span asp-validation-for="Airport_Name" class="text-danger"></span>
                        </div>

                        <div class=" col-4">
                            <ejs-textarea id="Personal_Address" maxlength="500" placeholder="Personal Address*" floatLabelType=Auto rows="1" ejs-for="@Model.Personal_Address"></ejs-textarea>
                            <span asp-validation-for="Personal_Address" class="text-danger"></span>
                        </div>

                        <div class=" col-4">
                            <ejs-textbox id="Phone_Number" showSpinButton="false" maxlength="30" placeholder="Phone Number" floatLabelType=Auto ejs-for="@Model.Phone_Number"></ejs-textbox>
                            <span asp-validation-for="Phone_Number" class="text-danger"></span>
                        </div>

                       
                        <div class=" col-4">
                            <ejs-textbox id="Emergency_Contact_Person" maxlength="100" placeholder="Emergency Contact Person*" floatLabelType=Auto ejs-for="@Model.Emergency_Contact_Person"></ejs-textbox>
                            <span asp-validation-for="Emergency_Contact_Person" class="text-danger"></span>
                        </div>
                       
                        <div class=" col-4">
                            <ejs-textbox id="Emergency_Contact_No" showSpinButton="false" maxlength="30" placeholder="Emergency Contact No.*" floatLabelType=Auto ejs-for="@Model.Emergency_Contact_No"></ejs-textbox>
                            <span asp-validation-for="Emergency_Contact_No" class="text-danger"></span>
                        </div>
                        <div class=" col-4">
                            <ejs-textarea id="Emergency_Contact_Address" maxlength="500" placeholder="Emergency Contact Address" rows="1" floatLabelType=Auto ejs-for="@Model.Emergency_Contact_Address"></ejs-textarea>
                            <span asp-validation-for="Emergency_Contact_Address" class="text-danger"></span>
                        </div>
                        <div class=" col-4">
                            <ejs-textarea id="Contact_Address" maxlength="500" placeholder="Contact Address" rows="1" floatLabelType=Auto ejs-for="@Model.Contact_Address"></ejs-textarea>
                            <span asp-validation-for="Contact_Address" class="text-danger"></span>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </form>
</div>
<script>

    function onfilteringN(e) {
        var query = new ej.data.Query();
        query = (e.text !== '') ? query.where('Text', 'contains', e.text, true) : query;
        e.updateData(@Html.Raw(JsonConvert.SerializeObject(@ViewBag.NationalityDrop)), query);
    }

</script>