AdminPanel/Controllers/UserMasterController.cs
using AdminPanel.CommonRepo;
using  AdminPanel.Models;
using AdminPanel.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;


namespace AdminPanel.Controllers
{
    [Authorize]
    [AuthorizeUser]
    public class UserMasterController : Controller
    {
        #region inject The Dependancy

        IEmployee EmpMaster;
        IUserMaster userMaster;
        IGeneral g;
        private readonly IHttpContextAccessor _httpContextAccessor;

       // ICommon common;


        public UserMasterController(IUserMaster _userMaster, IHttpContextAccessor httpContextAccessor, IEmployee _EmpMaster, IGeneral _g) //ICommon _common)
        {
            userMaster = _userMaster;
            EmpMaster = _EmpMaster;
            g = _g;
            _httpContextAccessor = httpContextAccessor;
           // common = _common;

        }
        #endregion


        public IActionResult Index(string id = null)
        {
            #region cerate view and bind dropdown
            try
            {


                VMUserMaser obj = new VMUserMaser();


                //ViewBag.Emp = EmpMaster.GetEmployeeList();

                ViewBag.sq = userMaster.DropDownSQ();
                ViewBag.Emp = userMaster.GetEmpCodeEmpName();
                ViewBag.Status = CommonDropdown.GetStatusDropdown();

                ViewBag.ORG = userMaster.GetOrganizationDropDownbyorgid();
                if (id != null)
                {

                    VMUserMaser Data = userMaster.USERMASTERBYID(id);

                    return View(Data);
                }
                var user = _httpContextAccessor.HttpContext.User;

                string orgCode = user.FindFirst("OrgCode")?.Value;

                if (orgCode == "" || orgCode == null)
                {
                    obj.MultipleDevice = 3;
                    obj.LoginAttempts = 3;
                    return View(obj);
                }
                obj.OrgCode = orgCode;
                obj.MultipleDevice = 1;
                obj.LoginAttempts = 3;
                return View(obj);


            }
            catch (Exception ex)
            {

                g.Write_Log_Into_Txt(ex.Message, "UserMasterController");
                g.InsertExcepstionlog(ex.Message, "UserMasterController");
                return View("Error");
            }
            #endregion
        }

        [HttpPost]
        public IActionResult Index(VMUserMaser Data, IFormFile Logo)
        {
            #region Insert and update the user master in the database
            try
            {

                ViewBag.sq = userMaster.DropDownSQ();
                ViewBag.Emp = userMaster.GetEmpCodeEmpName();
                ViewBag.Status = CommonDropdown.GetStatusDropdown();

                ViewBag.ORG = userMaster.GetOrganizationDropDownbyorgid();
                //    // Validate the uploaded file (if any)
                if (Logo != null)
                {
                    // Ensure the file is an image and is less than 3MB
                    var allowedFileTypes = new[] { "image/jpeg", "image/png" };
                    var maxFileSizeInMB = 3;
                    if (!allowedFileTypes.Contains(Logo.ContentType) || Logo.Length > maxFileSizeInMB * 1024 * 1024)
                    {
                        TempData["ShowPopup"] = true;
                        //ModelState.AddModelError("Logo", "Please upload a valid image file (JPG/PNG) less than 3MB.");
                        return View(Data); // Return the view with the current data and validation errors
                    }
                }

                // Insert or update the user master in the database
                ResponceMessage obj = userMaster.InserUpdate(Data, Logo);

                if (obj.code == 0)
                {

                    //DataTable UserData = userMaster.GetUsermasterDataTomail(obj.Sys_Code);
                    //List<TempletConfigration> Config = userMaster.GETEmailCONFIGRATION();
                    //List<Cangeneration> UserDdata = CommonRepo.CommonFunction.GetDataCANGENRATIONFormat(Config, UserData);


                    ////string rootPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Mailtemplate");
                    ////string emailBodyFilePath = Path.Combine(rootPath, "UserCreate.html");

                    ////string body = System.IO.File.ReadAllText(emailBodyFilePath);


                    ////string Emailbody = common.ReplacePlaceholders(UserDdata, body, "");

                    //string SenderEmailid = UserData.Rows[0]["Co_Email_ID"].ToString();
                    //if (SenderEmailid != null || SenderEmailid != "")
                    //{
                    //    common.mailalertUserCreation(UserDdata, SenderEmailid);
                    //}



                }

                if (obj.code == -1)
                {
                    return View(Data); // Return the view with the current data and validation errors
                }

                // Set appropriate TempData based on result
                if (obj.Message.Contains("INSERTED"))
                {
                    TempData["Output"] = "Record submitted successfully.";
                    return RedirectToAction("UserList");
                }
                else if (obj.Message.Contains("UPDATED"))
                {
                    TempData["Output"] = "Record updated successfully.";
                    return RedirectToAction("UserList");
                }
                else if (obj.Message.Contains("Dublicate"))
                {
                    TempData["Output"] = "Record already Exists.";
                    return RedirectToAction("UserList");
                }

                return View();

            }
            catch (Exception ex)
            {
                // Log the exception
                g.Write_Log_Into_Txt(ex.Message, "UserMasterController");
                g.InsertExcepstionlog(ex.Message, "UserMasterController");

                // Return the error view
                return View("Error");
            }
            #endregion
        }



        public IActionResult UserList()
        {
            #region Get all User Master List And bind in Grid
            try
            {
                ViewBag.userlist = userMaster.GETLISTUSERMASTER();

                return View();

            }
            catch (Exception ex)
            {

                g.Write_Log_Into_Txt(ex.Message, "UserMasterController");
                g.InsertExcepstionlog(ex.Message, "UserMasterController");
                return View("Error");
            }
            #endregion
        }



        [HttpGet]
        public IActionResult Delete(string id)
        {

            #region Delete The User Master in Db and update the status in D in db 
            try
            {
                ResponceMessage data = userMaster.DELETEUSERMASTER(id);
                // Set appropriate TempData based on result
                if (data.Message.Contains("UPDATED"))
                {
                    TempData["Output"] = "Deleted successfully";
                    return Json(data);
                }
                return Json(null);

            }
            catch (Exception ex)
            {

                g.Write_Log_Into_Txt(ex.Message, "UserMasterController");
                g.InsertExcepstionlog(ex.Message, "UserMasterController");
                return View("Error");
            }
            #endregion
        }

    }
}

AdminPanel/Views/UserMaster/UserList.cshtml
@using Syncfusion.EJ2
@addTagHelper *, Syncfusion.EJ2
@{
    ViewData["Title"] = "Userlist";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@{
    List<object> GridCommands = new List<object>();

    GridCommands.Add(new { type = "Edit", buttonOption = new { iconCss = "e-icons e-edit btnEdit", cssClass = "e-flat" } });

    GridCommands.Add(new { type = "Delete", buttonOption = new { iconCss = "e-icons e-delete btnDelete", cssClass = "e-flat" } });
}


@{
    string o = TempData["Output"] as string;
    bool showToast = !string.IsNullOrEmpty(o);
    string toastClass = string.Empty;

    if (showToast)
    {

        if (o.Contains("Error"))
        {
            toastClass = "bg-danger";
        }
        else if (o.Contains("Record already Exists."))
        {
            toastClass = "bg-danger";
        }
        else
        {
            toastClass = "bg-success";
        }
    }
}

<style>
    .bg-success {
        background-color: #28a745 !important;
        color: white;
    }


    .bg-danger {
        background-color: #dc3545 !important;
        color: white;
    }
</style>



@if (showToast)
{
    <ejs-toast id="element" cssClass="@toastClass" content="@o"></ejs-toast>
}







<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h4 class="p-2 m-0">
                USER LIST
            </h4>
        </div>
    </div>
</div>
<div id="Dilog" class="w-25"></div>
<div class="container-fluid mt-1 ">

    @* //dataSource="@ViewBag.OrgData" *@
    <ejs-grid id="Grid" dataSource="@ViewBag.userlist" allowSorting="true" allowPaging="true" allowFiltering="true" allowResizing="true" allowExcelExport="true" toolbar="@(new List<string>() {"Search","CustomButton"  })">
        <e-grid-editsettings></e-grid-editsettings>
        <e-grid-filtersettings type="Excel"></e-grid-filtersettings>
        <e-grid-pageSettings pageSize="5" pageSizes="true" />
        <e-grid-columns>
            <e-grid-column headerText="Option" width="105" commands="GridCommands"></e-grid-column>
            <e-grid-column field="UserID" visible=false isPrimaryKey="true" headerText="Id" textAlign="Right" width="105"></e-grid-column>
            <e-grid-column field="OrgCode" headerText="OrgName" width="200" textAlign="Right" allowFiltering="true"></e-grid-column>
            <e-grid-column field="UserName" headerText="UserName" width="200" textAlign="Right" allowFiltering="false"></e-grid-column>
            <e-grid-column field="Password" width="150" headerText="Password" textAlign="Left" allowFiltering="false"></e-grid-column>
            <e-grid-column field="EmpCode" width="150" headerText="Employee Name" textAlign="Right" allowFiltering="false"></e-grid-column>
            <e-grid-column field="IsAdministrator" width="104" headerText="IsAdministrator" allowFiltering="false"></e-grid-column>
            <e-grid-column field="MultipleDevice" width="150" headerText="Multiple Device" textAlign="Left" allowFiltering="false"></e-grid-column>
            <e-grid-column field="SecurityQuestion" width="150" headerText="SecurityQuestion" textAlign="Right" allowFiltering="false"></e-grid-column>
            <e-grid-column field="SecurityAnswer" width="150" headerText="SecurityAnswer" textAlign="Right" allowFiltering="false"></e-grid-column>
            <e-grid-column field="Status" width="104" headerText="Status" allowFiltering="false"></e-grid-column>
            @* <e-grid-column field="CreationDate" width="200" headerText="Created on" allowFiltering="false"></e-grid-column> *@

            @*   <e-grid-column field="IsADUser" width="104" headerText="IsADUser" allowFiltering="false"></e-grid-column>
            <e-grid-column field="IsEdit" width="104" headerText="IsEdit" allowFiltering="false"></e-grid-column>
            <e-grid-column field="IsDelete" width="104" headerText="IsDelete" allowFiltering="false"></e-grid-column> *@
            @*  <e-grid-column field="CreationDate" width="100" headerText="CreationDate" allowFiltering="false"></e-grid-column> *@


        </e-grid-columns>

    </ejs-grid>

</div>


<script>

    //For Toaster---
    document.addEventListener('DOMContentLoaded', function () {
        var showToast = @showToast.ToString().ToLower();

        if (showToast) {
            var toastObj = document.getElementById('element').ej2_instances[0];

            // Set the toaster position to top-right
            toastObj.position = {
                X: 'Right',
                Y: 'Top'
            };

            toastObj.show();
        }
    });



    $(document).ready(function () {
        var pid = null;
        var id = null
        var spanElement = $('<span class="e-btn-icon e-add e-icons e-icon-left "></span>');

        $(".e-tbar-btn-text").text("Add New");

        $("#Grid_CustomButton").prepend(spanElement);


        $("#Grid_CustomButton").on("click", function () {

            // Call your function here
            window.location.href = '@Url.Action("Index", "UserMaster")';
        });
    });

    // Handle Edit and Deletea
    function handleEditCommand(rowData) {

        // Example: Implement logic to handle edit command
        var grid = document.getElementById("Grid").ej2_instances[0];
        var data = grid.getRowObjectFromUID(rowData).data;

        var id = data.UserID;

        console.log(id);
        window.location.href = '@Url.Action("Index", "UserMaster")' + '?id=' + id;

        // $.ajax({
        //     "url": '@Url.Action("GetCitybyid", "City")',
        //     method: "GET",
        //     data: { id: id },
        //     dataType: 'json',
        //     success: function (data) {


        //         var redirectUrlWithId = data.redirectUrl + '?id=' + id;
        //               window.location.href = redirectUrlWithId;

        //     },
        //     error: function (err) {
        //         console.log("error: " + err)
        //     }

        // })
    }

    //delete Functionality sss---------------------------------

    var dialog = new ej.popups.Dialog({
        header: 'Confirm Delete',
        content: '<div>Are you sure you want to delete this record?</div>',
        buttons: [
            { buttonModel: { content: 'Yes', isPrimary: true }, click: onYesButtonClick, id: 'confirmDelete' },
            { buttonModel: { content: 'No' }, click: onNoButtonClick, id: 'cancelDelete' }
        ]

    });



    function clearDialogDiv() {
        var dialogDiv = document.getElementById("Dilog");
        if (dialogDiv) {
            while (dialogDiv.firstChild) {
                dialogDiv.removeChild(dialogDiv.firstChild);
            }
        }
    }


    function onNoButtonClick() {
        dialog.hide()
        clearDialogDiv();
        var popup = document.getElementById('Dilog');
        console.log(popup);
        var popupElement = popup.querySelector('w-25.e-control.e-popup.e-popup-.e-dialog');
        console.log(popupElement);
        if (popupElement) {
            alert("ggg");
            popup.removeChild(popupElement);
        }
    }

    function onYesButtonClick() {

        clearDialogDiv();

        if (id != "" && id != null) {
            $.ajax({
                "url": '@Url.Action("Delete", "UserMaster")',
                method: "GET",
                data: { id: id },
                dataType: 'json',
                success: function (data) {
                    window.location.reload();
                    // console.log(data);
                    if (data.Code = 0) {

                        window.location.reload();
                    }

                },
                error: function (err) {

                    console.log("error: " + err)
                }

            })
        }
        id = 0;


        var grid = document.getElementById('Grid').ej2_instances[0];
        grid.refresh();
        //Call Delete Ajax
    }

    function handleDeleteCommand(rowData) {
        var grid = document.getElementById("Grid").ej2_instances[0];
        dialog.appendTo('#Dilog');
        var data = grid.getRowObjectFromUID(rowData).data;
        console.log("Delete command clicked", data.UserID);
        id = data.UserID;

        if (dialog) {
            dialog.show(); // Show the dialog
        }

    }

    //Event when user Click On Edit or Delete Option Starts
    document.body.addEventListener("click", function (event) {
        var target = event.target;
        if (target.classList.contains("e-editbutton") || target.classList.contains("btnEdit")) {
            var rowData = target.closest("tr").getAttribute("data-uid");
            console.log(rowData);

            handleEditCommand(rowData);
        } else if (target.classList.contains("e-deletebutton") || target.classList.contains("btnDelete")) {

            var rowData = target.closest("tr").getAttribute("data-uid");
            handleDeleteCommand(rowData);
        }
    });


</script>